accessing
exceptionContext: aContext
	exceptionContext := aContext