accessing
exceptionProcess: aProcess
	exceptionProcess := aProcess